name: Run tests, dependency audit, CS fixer
on:
  push:
    branches-ignore:
      - *
    tags:
      - *
  workflow_run:
    workflows: ['check']
    types: ['completed']

jobs:
  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-20.04
    if: ${{ github.event.worklflow_run.conclusion == 'success' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
      - name: Build ZIP
        run: ./release/build_release_package.sh
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Shopgate Cart Integration SDK version ${{ github.ref }}
          draft: true
      - name: Upload ZIP to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./shopgate-cart-integration-sdk.zip
          asset_name: shopgate-cart-integration-sdk.zip
          asset_content_type: application/zip

# todo: Slack
